global_seed: 18
window_size: 10
input_size: 363 #no_data_feature * 2 * (window_size -1) + 3
num_parameters: 20
skip: 1
layer_size: 1024
output_size: 3
num_iterations: 100
checkpoint_iters: 10
train_ratio: 0.9
batch_size: 16
lr: 0.001
weight_decay: 0.005
scheduler_step_size: 40
num_epoch: 5

